// <auto-generated />
namespace ITNext___Online_PC_Market.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedImgURL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedImgURL));
        
        string IMigrationMetadata.Id
        {
            get { return "202008041525043_AddedImgURL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
